// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using ProjetoHELIOS_API.Data;

#nullable disable

namespace ProjetoHELIOS_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjetoHELIOS_API.Models.AcaoAutomatica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlertaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("DataHoraExecucao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("StatusAcao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("AlertaId");

                    b.ToTable("API_HELIOS_ACAO_AUTOMATICA", (string)null);
                });

            modelBuilder.Entity("ProjetoHELIOS_API.Models.Alerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcaoCorretiva")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("DataHoraAlerta")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("DataHoraResolucao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("ModuloId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NivelCriticidade")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("SensorId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("StatusAlerta")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TipoAlerta")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ModuloId");

                    b.HasIndex("SensorId");

                    b.ToTable("API_HELIOS_ALERTA", (string)null);
                });

            modelBuilder.Entity("ProjetoHELIOS_API.Models.Habitat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapacidadeTotal")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("StatusOperacional")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TipoHabitat")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("API_HELIOS_HABITAT", (string)null);
                });

            modelBuilder.Entity("ProjetoHELIOS_API.Models.LeituraSensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHoraLeitura")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("SensorId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("StatusLeitura")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("ValorLeitura")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("SensorId");

                    b.ToTable("API_HELIOS_LEITURA_SENSOR", (string)null);
                });

            modelBuilder.Entity("ProjetoHELIOS_API.Models.LogEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHoraEvento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NivelEvento")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("OrigemEvento")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("API_HELIOS_LOG_EVENTO", (string)null);
                });

            modelBuilder.Entity("ProjetoHELIOS_API.Models.ModuloHabitacional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapacidadeOcupantes")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("HabitatId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal?>("IndiceRisco")
                        .HasPrecision(5, 2)
                        .HasColumnType("DECIMAL(5,2)");

                    b.Property<string>("NivelRisco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NomeModulo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("OcupacaoAtual")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("StatusModulo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TipoModulo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("HabitatId");

                    b.ToTable("API_HELIOS_MODULO_HABITACIONAL", (string)null);
                });

            modelBuilder.Entity("ProjetoHELIOS_API.Models.Ocupante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Funcao")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("StatusOcupante")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("API_HELIOS_OCUPANTE", (string)null);
                });

            modelBuilder.Entity("ProjetoHELIOS_API.Models.RegraAlerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MensagemPadrao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NivelCriticidade")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("PesoRisco")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TipoSensor")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal?>("ValorMaximo")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<decimal?>("ValorMinimo")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL(10,2)");

                    b.HasKey("Id");

                    b.ToTable("API_HELIOS_REGRA_ALERTA", (string)null);
                });

            modelBuilder.Entity("ProjetoHELIOS_API.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("ModuloId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("OcupanteId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("StatusReserva")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ModuloId");

                    b.HasIndex("OcupanteId");

                    b.ToTable("API_HELIOS_RESERVA", (string)null);
                });

            modelBuilder.Entity("ProjetoHELIOS_API.Models.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataInstalacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("IntervaloLeituraSegundos")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal?>("LimiteMaximo")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<decimal?>("LimiteMinimo")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<int>("ModuloId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NomeSensor")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("StatusSensor")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TipoSensor")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ModuloId");

                    b.ToTable("API_HELIOS_SENSOR", (string)null);
                });

            modelBuilder.Entity("ProjetoHELIOS_API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<int>("NivelAcesso")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("StatusUsuario")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("API_HELIOS_USUARIO", (string)null);
                });

            modelBuilder.Entity("ProjetoHELIOS_API.Models.AcaoAutomatica", b =>
                {
                    b.HasOne("ProjetoHELIOS_API.Models.Alerta", "Alerta")
                        .WithMany("Acoes")
                        .HasForeignKey("AlertaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alerta");
                });

            modelBuilder.Entity("ProjetoHELIOS_API.Models.Alerta", b =>
                {
                    b.HasOne("ProjetoHELIOS_API.Models.ModuloHabitacional", "Modulo")
                        .WithMany("Alertas")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjetoHELIOS_API.Models.Sensor", "Sensor")
                        .WithMany("Alertas")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Modulo");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("ProjetoHELIOS_API.Models.LeituraSensor", b =>
                {
                    b.HasOne("ProjetoHELIOS_API.Models.Sensor", "Sensor")
                        .WithMany("Leituras")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("ProjetoHELIOS_API.Models.ModuloHabitacional", b =>
                {
                    b.HasOne("ProjetoHELIOS_API.Models.Habitat", "Habitat")
                        .WithMany("Modulos")
                        .HasForeignKey("HabitatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habitat");
                });

            modelBuilder.Entity("ProjetoHELIOS_API.Models.Reserva", b =>
                {
                    b.HasOne("ProjetoHELIOS_API.Models.ModuloHabitacional", "Modulo")
                        .WithMany("Reservas")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoHELIOS_API.Models.Ocupante", "Ocupante")
                        .WithMany("Reservas")
                        .HasForeignKey("OcupanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modulo");

                    b.Navigation("Ocupante");
                });

            modelBuilder.Entity("ProjetoHELIOS_API.Models.Sensor", b =>
                {
                    b.HasOne("ProjetoHELIOS_API.Models.ModuloHabitacional", "Modulo")
                        .WithMany("Sensores")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("ProjetoHELIOS_API.Models.Alerta", b =>
                {
                    b.Navigation("Acoes");
                });

            modelBuilder.Entity("ProjetoHELIOS_API.Models.Habitat", b =>
                {
                    b.Navigation("Modulos");
                });

            modelBuilder.Entity("ProjetoHELIOS_API.Models.ModuloHabitacional", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Reservas");

                    b.Navigation("Sensores");
                });

            modelBuilder.Entity("ProjetoHELIOS_API.Models.Ocupante", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("ProjetoHELIOS_API.Models.Sensor", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Leituras");
                });
#pragma warning restore 612, 618
        }
    }
}
